<?php
/**
* @file
* A description of what your module does.
*/

define('GF_USER_ROLE_MANAGER_GARDENER_ID', 18);
define('GF_USER_ROLE_WHOLESALE_CUSTOMER_ID', 19);

/**
 * Implements hook_uc_cart_alter().
 */
function gf_discount_uc_cart_alter(&$items) {
  $extra_10 = FALSE;
  if (user_has_role(GF_USER_ROLE_MANAGER_GARDENER_ID) 
    or user_has_role(GF_USER_ROLE_WHOLESALE_CUSTOMER_ID)) { 
    $extra_10 = TRUE; 
  }
  foreach ($items as $key => $item) {
    $discount = FALSE;

    if (isset($item->field_discount['und'])) {
      $field_discount_tid = $item->field_discount['und'][0]['tid'];
      $discount_term = taxonomy_term_load($field_discount_tid);
      $discount_raw_percent = $discount_term->name;
      $discount_percent = substr($discount_raw_percent, 0, strpos($discount_raw_percent, '%'));
      $discount = TRUE;
    }

    if ($discount) {
      if ($extra_10) {
        $discount_percent += 10;
      }

      $discount_coefficient = 1.0 - $discount_percent / 100;
      $item->price = $item->sell_price = $item->price * $discount_coefficient;
    } 
    elseif ($extra_10) {
      $discount_coefficient = 1.0 - 10 / 100;
      $item->price = $item->sell_price = $item->price * $discount_coefficient;
    }
  }
}

/**
 * Проверка на пользователя-новичка(еще не делал заказов).
 *
 * @return bool
 *   Возвращаем единичку, если заказов еще не было.
 */
function gf_discount_check_newbie($uid=NULL) {
  if (is_null($uid)) {
    global $user;
    $uid = $user->uid;
  }

  if ($uid < 2) return; // Юзер 1 нам тоже не интересен.
  $result = db_query('SELECT 1 FROM {uc_orders} WHERE uid = :uid',
    [':uid' => $uid])->fetchField();

  return !$result;
}
