<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_uc_cart_alter().
 */
function gf_discount_uc_cart_alter(&$items) {
  if (user_has_role(18) or user_has_role(19)) { $extra_10 = true; }

  foreach ($items as $key => $item) {

    $discount = FALSE;


    if (isset($item->field_discount['und'])) {
      $field_discount_tid = $item->field_discount['und'][0]['tid'];
      $discount_term = taxonomy_term_load($field_discount_tid);
      $discount_raw_percent = $discount_term->name;
      $discount_percent = substr($discount_raw_percent, 0, strpos($discount_raw_percent, '%'));
      $discount = TRUE;
    }


    if ($discount) {
      if ($extra_10) {
        $discount_percent += 10;
      }
      $discount_coefficient = 1.0 - $discount_percent / 100;
      $item->price = $item->price * $discount_coefficient;
      $item->sell_price = $item->price * $discount_coefficient;
    } elseif ($extra_10) {
      $discount_coefficient = 1.0 - 10 / 100;
      $item->price = $item->price * $discount_coefficient;
      $item->sell_price = $item->price * $discount_coefficient;
    }
  }
}
